### ISSUE TITLE
yarn.lock changes prevent vim-plug from updating vim-jsdoc

### ISSUE THREAD

**Issue by boblannon** [heavenshell/vim-jsdoc#103]
After running `PlugUpdate` most of my plugins updated successfully but I got an error for `vim-jsdoc`.

```
x vim-jsdoc:
    error: Your local changes to the following files would be overwritten by merge:
        lib/yarn.lock
    Please commit your changes or stash them before you merge.
    Aborting
    Updating 1aaa337..5487673
```

Just wanted to give a friendly heads-up!

If anyone else runs into this, the workaround is fairly simple, just 

```
cd ~/.vim/plugged/vim-jsdoc
git checkout -- yarn.lock
```

Then re-run `PlugUpdate`.

**Comment by heavenshell** [comment]
Thx for reporting! Add to README.md
