### ISSUE TITLE
不是编辑器的命令: commentstring< comments<

### ISSUE THREAD

**Issue by tzws** [heavenshell/vim-jsdoc#105]
执行 :e!

|| 处理 function <SNR>20_LoadFTPlugin 时发生错误:
|| 第    2 行:
|| E492: 不是编辑器的命令: commentstring< comments<

**Comment by heavenshell** [comment]
I Can't reproduce.
Works fine in my env.

Please write step to reproduce with minimal vimrc

```vim
set nocompatible
filetype off
set rtp=$VIMRUNTIME

set rtp+=./path/to/vim-jsdoc
filetype plugin indent on
```

**Comment by tzws** [comment]
reproduce steps:
1. use vim-jsonc\test-vimrc as vimrc, open some file
![WeChat Screenshot_20210303142942](https://user-images.githubusercontent.com/23232136/109763477-19040b00-7c2d-11eb-9b65-07ab5d55bcfc.png)

2. tabnew some json file

3. :set ft=jsonc
4. :e!
error occurs
![WeChat Screenshot_20210303143023](https://user-images.githubusercontent.com/23232136/109763695-6c765900-7c2d-11eb-989b-91d4187fe15f.png)

5. command history
![WeChat Screenshot_20210303143001](https://user-images.githubusercontent.com/23232136/109763675-62545a80-7c2d-11eb-9e01-a8b8117cf675.png)

**Comment by heavenshell** [comment]
Sorry this is **vim-jsdoc** 's issue.
I don't know about `vim-jsonc`.

Please ask to vim-jsonc's repository.
