### ISSUE TITLE
JsDoc is not an editor command for filetype=javascriptreact/typescriptreact

### ISSUE THREAD

**Issue by matt-savvy** [heavenshell/vim-jsdoc#116]
Hello, 

I get error `E492 Not an editor command: JsDoc` for jsx and tsx files. I was able to fix this for jsx only by tweaking my vimrc to use `'javascriptreact'` instead of `'javascript.jsx'` like so:
```
Plug 'heavenshell/vim-jsdoc', {
  \ 'for': ['javascript', 'javascriptreact', 'typescript'],
  \ 'do': 'make install'
\}
```
But adding `'typescriptreact'` doesn't seem to work for tsx.

**Comment by heavenshell** [comment]
@matt-savvy 

Thank you for reporting.
I'm bit a busy now, so please wait a moment :pray:
This weekend, I'll investigate this.

BTW are you using vim-plug?
