### ISSUE TITLE
ECMAScript6 method shorthand support

### ISSUE THREAD

**Issue by glifchits** [heavenshell/vim-jsdoc#14]
Doesn't work with new style method definitions. Here is an example -- given these functions, I typed `:JsDoc` and got the annotations as noted:

Old style:
```js
  /**
   * updateData
   *
   * @param data
   * @return {undefined}
   */
  updateData: function(data) {
    this.data = data;
    this.trigger(data);
  },
```

New style (shorthand):
```js
  /**
   * 
   *
   * @return {undefined}
   */
  updateData(data) {
    this.data = data;
    this.trigger(data);
  },
```

**Comment by heavenshell** [comment]
Try `feature_shorthand` branch.
https://github.com/heavenshell/vim-jsdoc/tree/feature_shorthand
This is an experimental implementation.

You should set `let g:jsdoc_allow_shorthand` to vimrc.
```
let g:jsdoc_allow_shorthand = 1
```

**Note**
This implementation has limitation.

```javasript
updateData(data);
```
If you type `:Jsdoc` to above, `jsdoc.vim` would generate like following.
```javascript
  /**
   * updateData
   *
   * @param data
   * @return {undefined}
   */
  updateData(data);
```

**Comment by glifchits** [comment]
:+1: love it, thank you! I'll raise any issues if they come up.

**Comment by heavenshell** [comment]
Merged to master branch.
