### ISSUE TITLE
g:jsdoc_access_descriptions Behavior Reversed

### ISSUE THREAD

**Issue by hbetts** [heavenshell/vim-jsdoc#15]
Reading through the README, my impression is that if `g:jsdoc_access_descriptions` is set to `2`, the resulting documentation for a private method would be `@private` or `@public`. However, on line [122](https://github.com/heavenshell/vim-jsdoc/blob/92dbef7e5e32857f84d527754c3650eb9fc1e612/autoload/jsdoc.vim#L122), the code uses `@access public` and `@access private`.

Testing this in my `.vimrc` file I can confirm that behavior.

Is this an indication that the documentation, or implementation, is incorrect?

**Comment by heavenshell** [comment]
Thx for pointing out.

Implementation was wrong.
dos also says 
```
Set value to 1 to turn on access tags like @access <private|public>`
Set value to 2 to turn on access tags like @<private|public>
```
I just fixed this problem.
