### ISSUE TITLE
Option to omit @return if no type given

### ISSUE THREAD

**Issue by glifchits** [heavenshell/vim-jsdoc#17]
I find it redundant to include the `@return {undefined}` for the many functions I have which do not have a return type. Can this be implemented?

**Comment by heavenshell** [comment]
Is `let g:jsdoc_return = 0` solve your problem?

**Comment by glifchits** [comment]
No because I would still like to include the `@return` type, but only if it is *not* `undefined`. What do you think?

**Comment by heavenshell** [comment]
humm, Sorry I still don't understand what is your requirement.

> but only if it is not undefined
So, what do you want to generate?

Just only `@return`?
And why `@return {undefined}` is redundant.

**Comment by glifchits** [comment]
When I am prompted for the return type, if I type nothing, the `@return` tag should be skipped. Currently, it will add `@return {undefined}`.

If you believe this is a silly request then please feel free to close it. I admit this is a matter of personal preference and therefore it might not be worth implemented it in this plugin.

**Comment by faceleg** [comment]
I'd like this feature. Saves me from having to go back and delete unwanted `@return` lines

**Comment by glifchits** [comment]
After closer investigation, I think this is in fact a bug.

```
let g:jsdoc_return=1
let g:jsdoc_allow_input_prompt=1
```

After prompts for the arguments...
```
Argument "argName" type: ...
Argument "argName" description: ...
```
Finally I get
```
Return type (blank for no @return):
```
I press **Enter** and then the documentation string appears:

```
/**
 * functionName
 *
 * @param {type} argName
 * @return {undefined}
 */
```
Even though I left it blank, it still generated a `@return`, against the promise.

**Comment by heavenshell** [comment]
@glifchits Thx I'll look into your PR this week end.

**Comment by ryanoasis** [comment]
:+1: At first I didn't quite agree but that's just because I am used to how it works now :stuck_out_tongue: 

But this change does seem to make sense given how the prompt reads :smile_cat:

**Comment by heavenshell** [comment]
@glifchits LGTM thx, merged.
