### ISSUE TITLE
ES6 jsdoc generation

### ISSUE THREAD

**Issue by Schniz** [heavenshell/vim-jsdoc#19]
in ES6 classes like
```javascript
class Foo {
  constructor(greeting) {
    this.greeting = greeting;
  }
  
  hello(name) {
    return this.greeting + ", " + name;
  }
}
```

it won't realize the return value nor the params

**Comment by heavenshell** [comment]
Try `let g:jsdoc_allow_shorthand = 1`.

**Comment by Schniz** [comment]
great! should have read the readme. sorry.
thanks for this one :smiley_cat: handy plugin

**Comment by heavenshell** [comment]
:smile_cat:
