### ISSUE TITLE
Default descriptions checking the argument name

### ISSUE THREAD

**Issue by IonicaBizau** [heavenshell/vim-jsdoc#24]
Is it possible to have a way to create default descriptions?

e.g. `if (field === "callback") { defaultDesc = "The callback function"; }`

And also, the type: `Function`.

This would be awesome! Thanks for great plugin. :four_leaf_clover:

**Comment by heavenshell** [comment]
No, but `let g:jsdoc_input_description = 1` allows you to input description interactively.
Is this solve your problem?

**Comment by IonicaBizau** [comment]
I know that, but I would like this feature: some default things for repetitive things (e.g. `callback).

Temporary, I hacked it this way:
```vim
 if (l:arg == "callback")
    let l:argType = "Function"
    let l:argDescription = "The callback function."
else
    let l:argType = input('Argument "' . l:arg . '" type: ', '', 'custom,jsdoc#listDataTypes')
    let l:argDescription = input('Argument "' . l:arg . '" description: ')
endif
```

**Comment by ryanoasis** [comment]
@IonicaBizau I can see what you mean. Maybe there is a place for something like this. A user configurable mapping to allow defaults such as the one you describe.

**Comment by heavenshell** [comment]
ah, now I see what you mean.

1. Set `let g:jsdoc_allow_input_prompt = 0` to .vimrc
2. Write following JavaScript code
```javascript
function foo(callback) {
}
```
3. Type `:JsDoc`

Then you want to insert custom description instead of default description.

Huuum, I think your hack is not good idea and I can't include to jsdoc.vim
```
function foo(callback, cb, errorCallback) {
}
```
If args are all callback your hack ignore second callback.
So, maybe we should think something like hook structure.

**Note following is a just idea.**
```
let g:jsdoc_custom_arg_hooks = {
  \  'callback|cb': {
  \    'description': 'cutsom description',
  \    'type': 'custom type'
  \  },
  \  'error': {
  \    'description': 'Error callback',
  \  }
\}
```
Dict key is regex and if key matched to defined signature, description and type would be replaced to default value.

**Comment by IonicaBizau** [comment]
@heavenshell  A setting like `g:jsdoc_custom_arg_hooks` in `.vimrc` is exactly what I imagine as well! Can you implement it? That will increase my productivity a lot. :smile: 

You know that joke:

> Over 1 year, the average Vim user saves 11 minutes in productivity.

> However, they lose 27 hours through evangelising Vim to non-users.

**Comment by heavenshell** [comment]
OK, I'll add my ToDo list, so stay tuned. 
If you can't wait my implementation, send me PR :smile:

**Comment by IonicaBizau** [comment]
@heavenshell Cool! 

> If you can't wait my implementation, send me PR

Right now, I don't know to write VimL code (the snippet I posted above was the first two lines written in VimL in my life). :smile:

**Comment by heavenshell** [comment]
@IonicaBizau 
Try `feature_custom_args ` branch.


Set following setting to your .vimrc
```viml
let g:jsdoc_custom_args_hook = {
  \ 'callback\|cb': {
  \   'type': ' {Function} ',
  \   'description': 'Callback function'
  \ }
\}
```
If above setting(dic) key matched to your function signature,
`type` and `description` would replaced.

```javascript
/**
 * foo
 *
 * @param bar
 * @param callback {Function} Callback function
 * @param cb {Function} Callback function
 * @return {undefined}
 */
function foo(bar, callback, cb) {
}
```
This is an experimental implementation.
So, if you catch bugs or problems, let me know.

**Comment by IonicaBizau** [comment]
@heavenshell For some reason it doesn't work for me. I updated the `autoload/jsdoc.vim` file and set the following in `.vimrc`:

```vim
let g:jsdoc_custom_args_hook = {
  \ 'callback\|cb': {
  \   'type': ' {Function} ',
  \   'description': 'The callback function.'
  \ },
  \ 'progress': {
  \   'type': ' {Function} ',
  \   'description': 'The progress function.'
  \ }
\}
```

`:echo g:jsdoc_custom_args_hook` outputs `{'progress': {'description': 'The progress function.', 'type': ' {Function} '}, 'callback\|cb': {'description': 'The callback function.', 'type': ' {Function} '}}`

But when I press <kbd>CTRL</kbd> + <kbd>L</kbd>, I see no difference.

**Comment by heavenshell** [comment]
ah, sorry currently it's only run at `let g:jsdoc_allow_input_prompt=0`.

**Comment by IonicaBizau** [comment]
@heavenshell Almost there. :smile: 

```js
/**
 * foo
 *
 * @name foo
 * @function
 * @param input
 * @param input
 * @param callback
 * @param callback {Function}  The callback function.
 * @param cb
 * @param cb {Function}  The callback function.
 * @param progress {Function}  The progress function.
 * @param progress
 * @return {undefined}
 */
function foo(input, callback, cb, progress) {

}
```

As you see, the fields are duplicated.

But I want to have the following: to be able to insert description, but if I just press enter (empty string), then search the default description.

**Comment by heavenshell** [comment]
Thx for reporting problem.
Strange...I'll look into it.

Would you show me your .vimrc(related jsdoc.vim settings).

>But I want to have the following: to be able to insert description, but if I just press enter (empty string), then search the default description.

So, you mean JsDoc.vim(interactive mode) might behave overwrite default description when press enter if dict key matched.
Please wait a while :smiley_cat:

**Comment by IonicaBizau** [comment]
[Here](https://github.com/IonicaBizau/dotfiles/blob/895a2f5edf58c48464695e34c991a54189a6c799/vim/.vimrc#L96-L100) and the following (not committed yet):

```vim
let g:jsdoc_custom_args_hook = {
  \ 'callback\|cb': {
  \   'type': ' {Function} ',
  \   'description': 'The callback function.'
  \ },
  \ 'progress': {
  \   'type': ' {Function} ',
  \   'description': 'The progress function.'
  \ }
\}
```

> So, you mean JsDoc.vim(interactive mode) might behave overwrite default description when press enter if dict key matched.

Yes! If I write something, then it has a greater priority than the default description.

Thanks! :cake:

**Comment by heavenshell** [comment]
Thx. reproduced.
Huum, maybe takes a while to fix.
I should reconsider implementation.

**Comment by heavenshell** [comment]
@IonicaBizau 
Fixed duplication and now you can use in interactive mode.
Could you try this?

**Comment by IonicaBizau** [comment]
Awww, this is soooo nice! :sparkles: 

However, there is one little thing that still should be fixed: it puts two spaces instead of one (e.g. `* @param a  {Function}  The callback function.`).

This is probably the last thing to fix from my side. :smile: Really great work.

**Comment by heavenshell** [comment]
>However, there is one little thing that still should be fixed: it puts two spaces instead of one (e.g. * @param a {Function} The callback function.).

Yep, expected behavior.
I Fixed to insert one space automatically.

Could you change your vimrc?
```diff
-'type': ' {Function} ',
+'type': '{Function}',
```

**Comment by IonicaBizau** [comment]
> Could you change your vimrc?

Hahaha! Cool! :sparkle: Exactly what I needed. Thanks again!

**Comment by heavenshell** [comment]
Merged to master.

**Comment by IonicaBizau** [comment]
:+1: :tada:
