### ISSUE TITLE
Errors when using plugin with input prompt disabled

### ISSUE THREAD

**Issue by naddeoa** [heavenshell/vim-jsdoc#25]
Thanks for the plugin, it is just what I'm looking for! That being said, out of the box I'm getting an error when I try to execute `:JsDoc` with `let g:jsdoc_allow_input_prompt=0` and I'm not sure how to go about debugging it.

```
~/workspace/D16GRodeoWebsite/src/AdvertisingReactComponents/src/advertiser/model.js" 115L, 3169C
Error detected while processing function jsdoc#insert..<SNR>113_hookArgs:
line   28:
E171: Missing :endif
Error detected while processing function jsdoc#insert:
line   95:
E706: Variable type mismatch for: l:lines
Error detected while processing function jsdoc#insert..<SNR>113_hookArgs:
line   28:
E171: Missing :endif
Error detected while processing function jsdoc#insert:
line   95:
E706: Variable type mismatch for: l:lines
```

It seems to work fine with `let g:jsdoc_allow_input_prompt=1` though.

**Comment by naddeoa** [comment]
I rolled back to commit `09edd82 - Fix the fields are duplicated.` and everything seems to work fine. I suspect something in commit `5f1d3d4 - Refactor...` causes the issue.

**Comment by heavenshell** [comment]
Oops, thx.
Fixed missing endif.
