### ISSUE TITLE
Sometimes the jsdoc comment is not generated properly

### ISSUE THREAD

**Issue by IonicaBizau** [heavenshell/vim-jsdoc#26]
Here is a case when the comment is incorrect:

```js
/**
 * ParentSearch
 *
 * @name ParentSearch
 * @function
 * @param path
 * @param search
 * @param options
 * @param callback {d} asd
 * @param progress {Function} The progress function.
 */
function ParentSearch(path, search, options, callback, progress) {
   // ...
}
```

I provided information about `path`, `search`, `options` and `callback` as well. The progress data is completed from defaults.

The first arguments descriptions and types are missing.

**Comment by heavenshell** [comment]
So .vimc settings are same as https://github.com/heavenshell/vim-jsdoc/issues/27#issuecomment-112117552 ?
`path` is not matched to anything.
Nothing should be to inserted.

**Comment by IonicaBizau** [comment]
@heavenshell Yes, same settings. I did insert custom description for `path` but still nothing was inserted.

**Comment by heavenshell** [comment]
Thx. reproduced.
I'll look into it.

**Comment by heavenshell** [comment]
Fixed. Could you try?

```javascript
/**
 * ParentSearch
 *
 * @param path {null} foo
 * @param search {}
 * @param options {}
 * @param callback {Function} The callback function.
 * @param progress {Function} The progress function.
 */
function ParentSearch(path, search, options, callback, progress) {
}
```

**Comment by IonicaBizau** [comment]
@heavenshell Nice! Works nice! :smile:

**Comment by heavenshell** [comment]
Thx for reporting :smile:

**Comment by IonicaBizau** [comment]
@heavenshell Thanks for fixing! :cake: :smile_cat: I **heavily** use this plugin daily. Then [`blah`](https://github.com/IonicaBizau/node-blah) generates the documentation (README.md, CONTRIBUTING.md etc).
