### ISSUE TITLE
Can't get it to work with vim 7.4 + janus setup

### ISSUE THREAD

**Issue by steadystatic** [heavenshell/vim-jsdoc#30]
I'm using pathogen via Janus and vim 7.4 - are there any known incompatibilities with other plugins?

I didn't see it in :scriptnames in cli vim and in MacVim I used the plugin listing plugin Headlights to show all my bundles and didn't see it there either.

Any ideas? Thanks!

**Comment by heavenshell** [comment]
> are there any known incompatibilities with other plugins?

No. JsDoc.vim does not depend on any plugins.
```viml
:set rtp
```
↑command shows runtimepath.
Is JsDoc.vim included in  runtimepath?

or
`:messages` shows any messages?

**Comment by heavenshell** [comment]
@steadystatic Any progress about this?
I'll close this issue because this is not a JsDoc.vim's problem.
