### ISSUE TITLE
Tools used to create animated gif?

### ISSUE THREAD

**Issue by MWers** [heavenshell/vim-jsdoc#32]
Nice plugin! Minor aside: Which tools did you use to create the animated gif screenshot with keypresses? Very cool.

Thanks!

**Comment by ryanoasis** [comment]
@MWers That was me, I used [keymon](http://code.google.com/p/key-mon/) (for the keypresses) + a custom [byzanz](http://linux.die.net/man/1/byzanz-record) script (for screencapture)

**Comment by heavenshell** [comment]
@MWers Solved?
Can I close this?

**Comment by MWers** [comment]
Issue solved. :)

Thanks for the info, @ryanoasis. And thanks for the excellent plugin, @heavenshell.

**Comment by heavenshell** [comment]
:+1:
