### ISSUE TITLE
Default message depending on the type

### ISSUE THREAD

**Issue by IonicaBizau** [heavenshell/vim-jsdoc#36]
Is it possible to add a way to define default descriptions depending on the type? Like, #24, but after providing the type I want to just press Enter and create the description automagically.

For example: `Object`, then I press twice <kbd>Enter</kbd> and I want to get `@param {Object} arg An object containing the following fields:` (which is supposed to be configured somewhere in `.vimrc`).

Btw, do you have a PayPal account? I'm happy to donate you some :heavy_dollar_sign: for making my life easier using this plugin. :smile:

**Comment by heavenshell** [comment]
@IonicaBizau 
Very interesting.
I implemented your idea.
Try this branch(https://github.com/heavenshell/vim-jsdoc/tree/feature_default_message). 
This is an experimentation and please report me if you have any problems.

Add following setting to your `.vimrc`
```viml
let g:jsdoc_type_hook = {
  \ 'object': 'An object containing the following fields',
  \ 'function': 'Callback function'
  \ }
```
If type is `obejct`, JSDoc.vim insert `An object containing the following fields` to description.

>Btw, do you have a PayPal account? I'm happy to donate you some :heavy_dollar_sign: for making my life easier using this plugin. :smile: 

Wow, Thank you very much.
It's very glad to hear that, but I don't have paypal account.
So if it's ok with you, please donate to Vim it self instead of me :smile: 
\# You know Vim is charity ware
http://www.vim.org/sponsor/index.php

**Comment by IonicaBizau** [comment]
@heavenshell Thanks! Almost there! :sparkle: The thing I still need is to be able to input a custom description (currently it seems that if I configure a hook for `Object`, then it doesn't ask me for the description).

Anyway, nice work! :smile_cat:

**Comment by heavenshell** [comment]
@IonicaBizau 
>The thing I still need is to be able to input a custom description (currently it seems that if I configure a hook for Object, then it doesn't ask me for the description).

Please explain to me little bit more?

```viml
let g:jsdoc_custom_args_hook = {
  \ 'callback\|cb': {
  \   'type': '{function}',
  \   'description': 'The callback function.'
  \ }
  \}
let g:jsdoc_type_hook = {
  \ 'object': 'An object containing the following fields',
  \ 'function': 'Callback function'
  \ }
```

Followings are steps to reproduce.
```javascript
function foo(bar, baz, callback) {
}
```
- `:JsDoc`
- `Argument "bar" type:`
- Input `object`
  - Then JSDoc.vim shows `Argument "baz" type:`
- input `number`
  - Then JSDoc.vim shows `Argument "baz" description:`
  - Input `baz` description
  - Then shows `Argument "callback" type:`
- hit return
  - Then shows `Argument "callback" description:`
  - hit return

Generated JSDoc is following.
```javascript
/**
 * foo
 *
 * @param {object} bar An object containing the following fields
 * @param {number} baz foo
 * @param {function} callback The callback function.
 */
function foo(bar, baz, callback) {
}
```
`@param {function} callback The callback function.` is from `let g:jsdoc_custom_args_hook`.

**Comment by IonicaBizau** [comment]
> Then JSDoc.vim shows Argument "baz" type:

Before this I want to get `Argument "bar" description:`–and if I only press <kbd>Enter</kbd>, it will be set to *An object containing the following fields*, otherwise (if I write something different), it will be set to what I wrote. So, basically, I still want to have the possibility to enter custom descriptions for type hooks. :dizzy:

**Comment by heavenshell** [comment]
@IonicaBizau 
OK, I see.
Please wait a while :smile:

**Comment by heavenshell** [comment]
@IonicaBizau 
Updated.

```viml
let g:jsdoc_type_hook = {
  \ 'object': {
  \   'description': 'An object containing the following fields',
  \   'force_override': 1,
  \ },
  \ 'function': 'Function description'
  \ }
```
If you set `'force_override': 1`, skip description prompt.
If you don't set `force_override` description prompt.

**Comment by IonicaBizau** [comment]
@heavenshell Works nice! Thank you sooooo much! :sparkles:

**Comment by heavenshell** [comment]
Merged to master. https://github.com/heavenshell/vim-jsdoc/commit/a0c8603c82c4a4e7700bbfb86d34e0b886528bac
