### ISSUE TITLE
Arrow Functions Not Supported

### ISSUE THREAD

**Issue by csaroff** [heavenshell/vim-jsdoc#37]
When attempting to document arrow functions I ran into this issue.  

When I run :JsDoc on the following methods, the displayed JsDoc is generated.
```javascript
/**
 *
 *
 * @return {undefined}
 */
const f = (arg1, arg2) => true;
/**
 * f
 *
 * @param arg1
 * @param arg2
 * @return {undefined}
 */
const f = function(arg1, arg2) {
    return true;
};
```

The arrow functions do not generate parameters or method names.

**Comment by heavenshell** [comment]
Currently arrow function does not work.

If you can't wail my update, patches are very welcome.

**Comment by csaroff** [comment]
Okay, thank you heavenshell.  I'll take a look at it this weekend, but I'm not sure that I'll have time to commit a patch.  I just wanted to add feature request, but I didn't know how to add the enhancement label.  Thanks for all of your work.  You're a hero!

**Comment by heavenshell** [comment]
@csaroff 
Try https://github.com/heavenshell/vim-jsdoc/tree/feature_arrow_function branch.
```viml
let g:jsdoc_enable_es6 = 1
```
```javascript
/**
 * foo
 *
 * @param {number} arg1
 * @param {number} arg2
 * @return {undefined}
 */       
const foo = (arg1, arg2) => true;
          
/**
 * f
 *
 * @param {number} arg1
 * @return {undefined}
 */       
const f = arg1 => true;
```

I'm not familar to ES6. So please send me feed back if you have any problem.

**Comment by jacoborus** [comment]
New branch works perfect for me

**Comment by heavenshell** [comment]
Thanks. :+1:

**Comment by heavenshell** [comment]
Note
From ver 0.5.0, `g:jsdoc_allow_shorthand` will be deprecated.
`let g:jsdoc_enable_es6 == 1` instead.

**Comment by csaroff** [comment]
Looks awesome man.  Thank you sooo much!

**Comment by heavenshell** [comment]
@csaroff 
Thx, I'll merge to master.

**Comment by heavenshell** [comment]
Merged.

**Comment by jacoborus** [comment]
I just realized that this feature breaks shorthand methods option. I opened #38
