### ISSUE TITLE
Enable parameters in shorthand methods with es6 feature

### ISSUE THREAD

**Issue by jacoborus** [heavenshell/vim-jsdoc#38]
`enable_es6`  feature is not detecting parameters in shorthand class methods

In this `method` only it allows you to add a description and type to return value, not to parameter

```js
class whatever {
  method (param) {
    // do something
  }
}
```

**Comment by heavenshell** [comment]
@jacoborus 
```javascript
class whatever {
  /**
   * method
   *
   * @param {number} param aaaa
   */
  method (param) {
  }
}
```
Works fine for me.
```viml
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 1
```

**Comment by heavenshell** [comment]
Please show me step to reproduce.

**Comment by jacoborus** [comment]
I'm sorry @heavenshell , my fault. I was trying to launch jsdoc from inside the function instead from first line. Plugin works perfect =)

**Comment by heavenshell** [comment]
No problem :+1:
