### ISSUE TITLE
Support ES6 class methods

### ISSUE THREAD

**Issue by IonicaBizau** [heavenshell/vim-jsdoc#41]
````js
class Parser {

    constructor (app) {
       ...
    }

    // This should be able to generate a nice comment
    parse (cb) {
      ...
    }
}
````

Is this a known issue or it's something that needs to be improved?

**Comment by heavenshell** [comment]
```viml
let g:jsdoc_enable_es6=1
```
```javascript
class Parser {

    constructor (app) {
       ...
    }

    // This should be able to generate a nice comment
    /**
     * parse
     *
     * @param {function} cb The callback function.
     * @return {undefined}
     */
    parse (cb) {
      ...
    }
}
```

**Comment by IonicaBizau** [comment]
Ohhh, thanks!! :dizzy: 

I love so much this plugin! :smile:

**Comment by IonicaBizau** [comment]
@heavenshell This looks broken––I did enable es6 using `let g:jsdoc_enable_es6=1`.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/2864371/11919816/197cfba2-a765-11e5-932f-9acc626ce0ae.png)

**Comment by heavenshell** [comment]
@IonicaBizau 
Can not reproduced.
<img width="359" alt="2015-12-21 23 22 36" src="https://cloud.githubusercontent.com/assets/56591/11932568/c8011b34-a839-11e5-8ee4-f4d0c5ef18b1.png">

Can you show me your vimrc(jsdoc.vim settings) and step to reploduce?

**Comment by IonicaBizau** [comment]
@heavenshell [This](https://github.com/IonicaBizau/dotfiles/blob/master/vim/.vimrc) is my `.vimrc`.
[Here](https://github.com/IonicaBizau/dotfiles/blob/master/vim/.vimrc#L77-L103) are the jsdoc related options.

**Comment by heavenshell** [comment]
@IonicaBizau 
Copy your vimrc settings, move to `parse ()` line, exec `:JsDoc` and hit all enter.
But still can't reploduce it.

![image](https://cloud.githubusercontent.com/assets/56591/11933832/aef45d4c-a841-11e5-9aa8-d073c8659f8e.png)

**Comment by IonicaBizau** [comment]
@heavenshell Hmm, thanks. Will try to debug the problem. It does work on my desktop computer, but not on my laptop. I did `NeoBundleUpdate` and still no change...

**Comment by heavenshell** [comment]
@IonicaBizau 
Thx.
What the difference between your laptop and desktop. 
vimrc, other Vim plugin or Vim version etc.

>I did NeoBundleUpdate and still no change...

JSDoc.vim has no dependency to other plugin, but if conflicted, please let me know.

**Comment by IonicaBizau** [comment]
@heavenshell Finally I solved this problem. I couldn't find any difference between my desktop and laptop, but I refactored my `.vimrc` from scratch and the issue disappeared. Thanks once again for this amazing plugin! :sparkles:

**Comment by heavenshell** [comment]
@IonicaBizau Nice to hear that. Thx.
