### ISSUE TITLE
jsdoc_input_description default value

### ISSUE THREAD

**Issue by kyohei8** [heavenshell/vim-jsdoc#42]
I have a little question.

Its source code, 

```
if !exists('g:jsdoc_input_description')
  let g:jsdoc_input_description = 0
endif
```

but, README file(or doc file) says `g:jsdoc_input_description` is default value is `1`.

which is correct??

**Comment by ryanoasis** [comment]
Good catch :+1: 

Looks like it has always been default of `0` in the code.

Originally `0` in doc: https://github.com/heavenshell/vim-jsdoc/blob/639d21b995e06f5c00f824596995c85bec6058b0/doc/jsdoc.txt#L79

but somehow changed to `1` in doc: https://github.com/heavenshell/vim-jsdoc/blob/30a6d0d1755a1d4677c1d7beee5112f4d1234901/doc/jsdoc.txt#L91 but remained as default `0` in code.

Also yes the readme is also incorrect in this case.

**Comment by heavenshell** [comment]
Fix docs. Thx for report.
Nice catch!

**Comment by kyohei8** [comment]
Thanks a lot! :+1:
