### ISSUE TITLE
ES6 class support

### ISSUE THREAD

**Issue by tjwudi** [heavenshell/vim-jsdoc#44]
ES6 is now very popular and I think it is reasonable to support both `function` and `class` class definition. Is it in the plan? If not, I could investigate how to implement this. :)

**Comment by heavenshell** [comment]
What should we generate from class signature.
Could you show me example?

And sorry I'm not familiar with ES6.
What do you mean about `function` class.
Could you show me example of `function` class signature and expected behavior?

**Comment by ryanoasis** [comment]
I think @tjwudi is referring to arrow function expressions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Classes: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by heavenshell** [comment]
@ryanoasis 
Thx.
Arrow function has been supported.

>classes

I want to know what JSDoc.vim should generate.

Currently following JSDoc generate.
```javascript
/**
 *
 *
 * @return {undefined}
 */
class Foo {
}
```

**Comment by Reewr** [comment]
@heavenshell 

With the JSDoc 3.4.0 (latest version on NPM), I was able to parse the following into a class

```javascript
/**
 * Description
 */
class Foo {

  /**
   * @param {string} foo description
   * @param {string} bar description
   * @return {Foo}
   */
  constructor(foo, bar) {
    this.foo = foo;
    this.bar = bar;
  }
}
```

JSDoc will in this case correctly pick up the constructor (@return {Foo} on the constructor is probably not necessary). If the class has no constructor, JSDoc will make a constructor without arguments.

I have not tried your plugin yet as I just found it, but I am currently installing it. What happens if you have the following:

```javascript
class Foo extends Bar {

}
```

Will JSDoc.vim find out that it Foo extends bar and add `@extends Bar`?

**Comment by heavenshell** [comment]
@Reewr Nice. Thanks for suggestion. 
I'll start improve this issue.
BTW Pull requests are very welcome :smile: 

>JSDoc will in this case correctly pick up the constructor (@return {Foo} on the constructor is probably not necessary). If the class has no constructor, JSDoc will make a constructor without arguments.

I think describing `return {Foo}` at constructor is strange.
You know constructor always returns it self.

>Will JSDoc.vim find out that it Foo extends bar and add @extends Bar?

Currently not.
But I think it should be generate like following.
```javascript
/**
 * Foo
 *
 * @extend Bar
 */
class Foo extends Bar {
  /**
   * @param {string} foo description
   * @param {string} bar description
   */
  constructor(foo, bar) {
    this.foo = foo;
    this.bar = bar;
  }
}
```
What do you think?

**Comment by Reewr** [comment]
That's great. I've used this plugin somewhat now and I found it to be really useful. 

> What do you think?

I think it looks good.

Will you also support for static functions in classes?

```js
class Foo {
  /**
   * Description
   *
   * @static
   * @param {string} foo description
   * @returns {string} description
   */
  static fooStatic(foo) {}
}
```

I would help you out with a pull request, but I've just started using Vim and absolutely no clue on how VimL works yet.

**Comment by heavenshell** [comment]
>Will you also support for static functions in classes?

OK, I'll start improve `static function` after this issue solve.
I'll add it to my todo list.
Stay tuned.

>I would help you out with a pull request, but I've just started using Vim and absolutely no clue on how >VimL works yet.

Don't mind :smile_cat:

**Comment by heavenshell** [comment]
bfac691e27545194270f62b55036785ea7209947 support class and static.
```javascript
/**
 * Foo
 */
class Foo {
  /**
   * foo
   *
   * @static
   * @param {} bar
   * @param {} baz
   * @returns {undefined}
   */
  static foo(bar, baz) { } // static method
}
```

**Comment by bogas04** [comment]
Sorry for bringing this up again, but we still have one part that isn't supported by vim-jsdoc, i.e. [Function Definition Shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions)

```js
let Person = {
  talk() {
    console.log("Talking!");
  }
};
```
