### ISSUE TITLE
ES6 Generator functions

### ISSUE THREAD

**Issue by Reewr** [heavenshell/vim-jsdoc#53]
Generating documentation for ES6 Generator functions doesn't work properly. 

```javascript
let generatorFn = function* (arg1, arg2) {};
```

Using JsDoc on the above function only adds description and return and doesn't recognize the arguments. This is most likely due to the function regex not considering '*' a valid character in between `function` and parenthesis.

**Comment by heavenshell** [comment]
Thx for reporting.
I'll look into it later.

Patches are very welcome :smile:
