### ISSUE TITLE
Unable to generate @public or @private

### ISSUE THREAD

**Issue by tribou** [heavenshell/vim-jsdoc#56]
I haven't been able to get `@public` or `@private` options generated using the following config:

```vim
let g:jsdoc_allow_input_prompt = 1
let g:jsdoc_input_description = 1
let g:jsdoc_access_descriptions = 2
let g:jsdoc_underscore_private = 1
let g:jsdoc_enable_es6 = 1
```

Is there supposed to be an additional prompt when using the `:JsDoc` command?

**Comment by heavenshell** [comment]
Sorry for late response.

Add following settings to my .vimrc.
```viml
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 1
let g:jsdoc_input_description = 1
let g:jsdoc_access_descriptions = 2
let g:jsdoc_underscore_private = 1
```
```javascript
function _foo() {
} 
```
Type `:JsDoc` and generate like followings.
```javascript
/**
 * _foo
 *
 * @private
 */
function _foo() {
} 
```
Could you show me steps to reproduce?

**Comment by heavenshell** [comment]
Not reproduced.
If you reproduced, reopen this issue.
