### ISSUE TITLE
Autoformatting support

### ISSUE THREAD

**Issue by ajwhite** [heavenshell/vim-jsdoc#57]
Would love for an option to allow automatic formatting. Currently going in by hand afterwards to make alignments

![screen shot 2016-04-27 at 11 48 09 pm](https://cloud.githubusercontent.com/assets/656630/14874863/8a92eaea-0cd2-11e6-8f5f-fdc97b67f68a.png)

**Comment by heavenshell** [comment]
Sorry for late response.

>Would love for an option to allow automatic formatting. Currently going in by hand afterwards to make alignments

No plan to support formatting.
Formatting is not JsDoc.vim's responsibility.

Maybe [EasyAlign](https://github.com/junegunn/vim-easy-align) will solve your problem.

```viml
let g:easy_align_ignore_groups = ['!Comment', 'String']
```
