### ISSUE TITLE
how to make :JsDoc append @author or @date automatically?

### ISSUE THREAD

**Issue by onweer** [heavenshell/vim-jsdoc#59]
how to make :JsDoc append @author or @date automatically?

**Comment by heavenshell** [comment]
Currently can't generate `@author` or `@date`.

But we should introduce something like `user_defined_tags`.

```viml
let g:jsdoc_user_defined_tags = [
\ {'@author': 'YOUR NAME'},
\ {'@date': strftime('%F')
\ ]
```

I'll add to my todo list.

**Comment by onweer** [comment]
Thanks !.

**Comment by heavenshell** [comment]
@onweer 
Try `feature_user_defined_tags` branch.

Set following settings to your `.vimrc`.
```viml
let g:jsdoc_user_defined_tags = {
  \ '@author': 'YOUR NAME',
  \ '@date': strftime('%F')
  \ }      
" }}}       


```

**Comment by heavenshell** [comment]
Merged to master
https://github.com/heavenshell/vim-jsdoc/commit/e1ac68a52abc7d3a1fc6d613f696db142f295cdb
