### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Torwori** [heavenshell/vim-jsdoc#60]
It'd be nice if the plugin had typescript support (automatically detect types for parameter and return value, if specified).

**Comment by heavenshell** [comment]
Yeah, currently I'm working to support TypeScript.

**Comment by heavenshell** [comment]
@Torwori 
Could you try https://github.com/heavenshell/vim-jsdoc/tree/feature_typescript branch?

**Comment by Torwori** [comment]
I'll check it out tomorrow after work, sorry for the delay.

**Comment by Torwori** [comment]
Hey, just tried it out, seems to be working ok. :+1:

It would be even better if it automatically read types from the function signature, but if that's too much of a hassle then this is good enough.

**Comment by heavenshell** [comment]
@Torwori Thx for your feedback!

>It would be even better if it automatically read types from the function signature,

Could you explain me more?

```javascript
function foo(foo: string): string {
  return 'foo'
}
```
This would be like following.
```javascript
/**
 * foo
 *
 * @param {string} foo
 * @returns {string}
 */
function foo(foo: string): string {
  return 'foo'
}
```
`{string}` are read from signature.

**Comment by Torwori** [comment]
```vim
let g:jsdoc_allow_input_prompt = 1
let g:jsdoc_input_description = 1
let g:jsdoc_additional_descriptions = 1
let g:jsdoc_access_descriptions = 2
let g:jsdoc_underscore_private = 1
let g:jsdoc_enable_es6 = 1
```

These are the settings I used, I had to enter the types manually.

**Comment by heavenshell** [comment]
@Torwori 
Thx. I'll start investigation.

**Comment by heavenshell** [comment]
@Torwori 
```viml
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 1
let g:jscoc_return = 1
let g:jsdoc_input_description = 1
let g:jsdoc_access_descriptions = 2
let g:jsdoc_underscore_private = 1
```

```javascript
function foo(foo: string = 'foo', bar: number = 1): string {
  return 'foo'
}
```

```javascript
/**
 * Foo
 *
 * @public
 * @param {string} foo foo description
 * @param {number} bar bar description
 * @returns {string} foo string
 */
function foo(foo: string = 'foo', bar: number = 1): string {
  return 'foo'
}
```

Looks good to me.

Hit tab key when `Argument "foo" type:` shows then output typed candidates.

**Comment by Torwori** [comment]
Ah, I didn't know you could press tab. :+1:

**Comment by heavenshell** [comment]
@Torwori 
Thx. Merged to master.

**Comment by xahon** [comment]
JsDoc doesn't appear if cursor on line like `public someFunc() : void`

**Comment by heavenshell** [comment]
@xahon 
https://github.com/heavenshell/vim-jsdoc/blob/master/test/test.ts#L36
open above file and execute `:JsDoc`.

```typescript
  /**
   * baz
   *
   * @param {string} [arg1='foo']
   * @param {number} [arg2=100]
   * @returns {void}
   */
  public baz(arg1: string = 'foo', arg2: number = 100): void {
  }
```

It seems works fine.
