### ISSUE TITLE
What is the test framework?

### ISSUE THREAD

**Issue by myklemykle** [heavenshell/vim-jsdoc#62]
Hello,

Sorry if this is a dumb question ... I'm doing some private extensions of vim-jsdoc to support our company's private extensions of JsDoc.  I would like to develop tests for what I'm doing.  I see that there are example .js files in the test/ directory, but I don't see any script to automate testing against those.  What test framework are you using?  How can I run these tests?  

Thanks,
-mykle-

**Comment by heavenshell** [comment]
@myklemykle 
I'm sorry, currently I did't write tests.
I know I should write tests with E2E test, something like vader.vim

currently, `test/*` runs handly.
open test file and just run `:JsDoc` command.

**Comment by myklemykle** [comment]
That's okay, i can test manually.  Thanks for letting me know.

-m-
--
IM IN MY IPHON MISPELIN UR W0RDZ
