### ISSUE TITLE
Param defaults as optional?

### ISSUE THREAD

**Issue by codeinabox** [heavenshell/vim-jsdoc#64]
Using the ES6 code for handling defaults and `:JsDoc` with prompts enabled it generates the following

```js
  /**
   * getChildren
   *
   * @param {int} id
   * @param {int} pageSize=10
   * @param {int} page=1
   * @returns {Promise}
   */
  getChildren(id, pageSize = 10, page = 1) {

```

However as per the [JSDoc documentation](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values), should those params with defaults be listed as optional? ie

```js
  /**
   * getChildren
   *
   * @param {int} id
   * @param {int} [pageSize=10]
   * @param {int} [page=1]
   * @returns {Promise}
   */
  getChildren(id, pageSize = 10, page = 1) {

```

**Comment by heavenshell** [comment]
@codeinabox 
ah, thx for reporting issue.

I'll fix it later, stay tuned 😊

**Comment by heavenshell** [comment]
@codeinabox 
Could you try `fix/default_params` branch?

**Comment by codeinabox** [comment]
Still getting the same output

**Comment by heavenshell** [comment]
fmmm, strange.

- open ./test/test.js
- move cursor to `function defaultParams(arg, arg1 = 'foo', arg2 = 100) {}` line
- type `:Jsdoc`

```javascript
/**
 * defaultParams
 *
 * @param {string} arg
 * @param {string} [arg1='foo']
 * @param {number} [arg2=100]
 * @returns {undefined}
 */
```

Could you show me your jsdoc.vim settings?

**Comment by codeinabox** [comment]
I tried that but get 
```js
/**
 * defaultParams
 *
 * @param {string} arg
 * @param {string} arg1='foo'
 * @param {string} arg2=100
 */
function defaultParams(arg, arg1 = 'foo', arg2 = 100) {}
```

Settings are 

```viml
Plugin 'heavenshell/vim-jsdoc'
	" vim-jsdoc {{{
	let g:jsdoc_allow_input_prompt = 1
	let g:jsdoc_enable_es6 = 1
	" }}}

```

**Comment by heavenshell** [comment]
@codeinabox 
Thx. Did you try https://github.com/heavenshell/vim-jsdoc/tree/fix/default_params branch?

**Comment by codeinabox** [comment]
Yes. Went into .vim/bundle/vim-jsdoc and switched to that branch when I tried earlier.

**Comment by heavenshell** [comment]
@codeinabox 
Thx, I couldn't reproduced...

So, I add print debug statement.
Update `fix/default_params` branch.

Run jsdoc and `:messages`.
than, debug messages shows.
Could you paste debug messages?

**Comment by codeinabox** [comment]
Nothing seems to come up when I invoke `:messages`

**Comment by heavenshell** [comment]
I think your plugin manager is something wrong.
I don't know what plugin manager are you using.

> Yes. Went into .vim/bundle/vim-jsdoc and switched to that branch when I tried earlier.

Is this right way to switch branch?
I think you did not switch branch.

**Comment by heavenshell** [comment]
Merge to master.
