### ISSUE TITLE
ES6 Destructured Object Function Argument

### ISSUE THREAD

**Issue by floscr** [heavenshell/vim-jsdoc#67]
Hi,

Right now destructured function parameters are broken:
```js
const obj = {
  a: 'a',
  b: 'b',
  other: '...',
}

/**
 * DocBlock
 *
 * @param {} {a
 * @param {} b}
 */
function objectAB ({ a, b }) {
  return a + b
}

objectAB(obj)
```

Of course this is a matter of opinion, but I think the spread object argument should be one parameter like

```js
/**
 * DocBlock
 *
 * @param {obj} { a, b } Param Comment
 */
```

**Comment by heavenshell** [comment]
Thx for reporting.
I'll look into it.

**Comment by heavenshell** [comment]
Still working this.
But it too complecated... 😢

**Comment by heavenshell** [comment]
ver2.0.0 was released.
This problem fixed
