### ISSUE TITLE
How to use it in vue?

### ISSUE THREAD

**Issue by Cyperwu** [heavenshell/vim-jsdoc#69]
I'm currently using vue, how can I use this plugin in vue?

**Comment by heavenshell** [comment]
Sorry for late response.
Install jsdoc.vim and read the docs.

**Comment by imfangli** [comment]
I haven't found the way to use this awesome plugin in `.vue` file too, I already read the docs... 😭

**Comment by heavenshell** [comment]
@imfangli 

I don't know about `.vue` file, but you can do something like followings.

```html
<script>
export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>
```

```
$ vim sample.vue
:set ft=javascript
2j
:JsDoc
```

```html
<script>
export default {
  /**
   * data
   *
   * @returns {undefined}
   */
  data () {
    return {
      msg: 'Hello world!'
    }
  }
}
</script>
```

If you don't want `set ft=javascript` every time, put following settings at your `.vimrc`.
```
autocmd BufRead,BufNewFile *.vue setlocal filetype=javascript.html 
```

**Comment by imfangli** [comment]
@heavenshell

**Comment by heavenshell** [comment]
@imfangli Welcome ☺️
