### ISSUE TITLE
TypeScript inputs configuration

### ISSUE THREAD

**Issue by Edo78** [heavenshell/vim-jsdoc#74]
Hi,
I'm trying to configure the plugin to automatically get the input types from the typescript declaration but to have it asking me the description of each param.

Sadly if I set
```
let g:jsdoc_allow_input_prompt = 0
let g:jsdoc_input_description = 1

```
the plugin doesn't ask for the description but if I try
```
let g:jsdoc_allow_input_prompt = 1
let g:jsdoc_input_description = 1

```
then it ignores the types specified in the function.

Am I missing something?

**Comment by heavenshell** [comment]
@Edo78 
Did you set following?
```
let g:jsdoc_enable_es6 = 1
```

**Comment by Edo78** [comment]
yes, I do because I declare my functions with the fat arrow syntax

**Comment by heavenshell** [comment]
@Edo78 Thx!
```
class Bar extends Foo implements IFoo {
  private foo(arg1: string, arg2: number = 0): void {
  }
}
```
In my settings, generated like following.

```
class Bar extends Foo implements IFoo {
  /**
   * foo
   *
   * @param {string} arg1
   * @param {number} [arg2=0]
   * @returns {void}
   */
  private foo(arg1: string, arg2: number = 0): void {
  }
}
```

```
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 0
```

Could you show me your vimrc(related with jsdoc.vim)?
and generated output?

**Comment by Edo78** [comment]
```
const testFunction = (par1: string) => {
    console.log(par1)
}
```
With a config like this
```
" let g:jsdoc_allow_input_prompt = 1
let g:jsdoc_input_description = 1
let g:jsdoc_param_description_separator = ': '
let g:jsdoc_additional_descriptions = 1
let g:jsdoc_enable_es6 = 1
```
the plugin ask me for a description and generate
```
/**
 * test
 *
 * @name testFunction
 * @function
 * @param {string} par1
 * @returns {undefined}
 */
const testFunction = (par1: string) => {
    console.log(par1)
}
```
while enabling `let g:jsdoc_allow_input_prompt = 1` ask for parameters type and description (also for return type and description) and generate
```
/**
 * test
 *
 * @name testFunction
 * @function
 * @param {x} par1: xxx
 * @returns {x} xxx
 */
const testFunction = (par1: string) => {
    console.log(par1)
}
```

**Comment by heavenshell** [comment]
Sorry bit confused.
What's is your problem?

Settings.
```
let g:jsdoc_enable_es6 = 1
let g:jsdoc_allow_input_prompt = 0
let g:jsdoc_input_description = 1
let g:jsdoc_param_description_separator = ': '
let g:jsdoc_additional_descriptions = 1
let g:jsdoc_enable_es6 = 1
```

```
const testFunction = (par1: string) => {
  console.log(par1)
}
```
1. Move cursor to testFunction line
1. Type `:JsDoc`
1. Prompt `Description: `
1. Type `aaa<CR>`
```
/**
 * aaa
 *
 * @name testFunction
 * @function
 * @param {string} par1
 * @returns {undefined}
 */
const testFunction = (par1: string) => {
  console.log(par1)
}
```
Works fine.

**Comment by heavenshell** [comment]
Please show me step by step and what is your expected behavior.

**Comment by Edo78** [comment]
Your example didn't prompt for the argument description.

I want the plugin to get the types from the code because I don't want to write them again but to ask me the description of each argument.

**Comment by heavenshell** [comment]
>I want the plugin to get the types from the code because I don't want to write them again but to ask me the description of each argument.

```
 * @param {string} par1
 * @returns {undefined}
```
These types are from signature(`par1: string`).

**Comment by heavenshell** [comment]
Ah, I got it.

You do want not input types but you want type description your self?

**Comment by heavenshell** [comment]
Sorry currently, there is no way to get type from signature.
input nothing(just hit enter key) generates `undefined`.

Adding new global flag is easy but we have too many already flags.
Do you have any idea to improve this? If design is good, I'll implement.

**Comment by Edo78** [comment]
I was thinking about a modification [here](https://github.com/heavenshell/vim-jsdoc/blob/a164cb4c14b9063e82b6ccba96b4bc8b3a6d8f73/autoload/jsdoc.vim#L458)

```
index fc93896..656f76e 100644
--- i/autoload/jsdoc.vim
+++ w/autoload/jsdoc.vim
@@ -459,7 +459,11 @@ function! jsdoc#insert() abort
         if l:arg['type'] != ''
           let s:candidate_type = l:arg['type']
         endif
-        let l:argType = input('Argument "' . l:arg['val'] . '" type: ', '', 'custom,jsdoc#listDataTypes')
+        if s:candidate_type == ''
+            let l:argType = input('Argument "' . l:arg['val'] . '" type: ', '', 'custom,jsdoc#listDataTypes')
+        else
+            let l:argType = s:candidate_type
+        endif
         redraw | echo ''
         let l:argDescription = s:build_description(l:argType, l:arg)
         if g:jsdoc_custom_args_hook == {}
```
This way if the script found a candidate_type then it use it without even asking but keep asking for a description of the arg.

I'm not sure if this could break something else

**Comment by Edo78** [comment]
I just created a [PR](https://github.com/heavenshell/vim-jsdoc/pull/75)

**Comment by heavenshell** [comment]
2.0.0 was released.
input intaractive was deprecated
