### ISSUE TITLE
Return Type Includes Arrorw with Flow and Arrow Functions

### ISSUE THREAD

**Issue by DeedleFake** [heavenshell/vim-jsdoc#77]
Running `:JsDoc` on

```javascript
const example = (key: string, val: string): string => {
  return val
}
```

produces the comment

```javascript
/**
 * example
 *
 * @param {string} key
 * @param {string)} val
 * @returns {string =>}
 */
```

**Comment by heavenshell** [comment]
Thx for reporting.
Known issue and it's hard to fix.

Please stay tuned.

P.S.
PR are very welcome.

**Comment by malakada** [comment]
Extra: in this example:

```
const Container = ({ message: string }): JSX.Element => (
  <div>{message}</div>
);
```

Running `:JsDoc` would generate this:

```
/**
 * Container
 *
 * @param {string})} {message
 * @returns {JSX.Element => (}
 */
```

A more desirable output would be:

```
/**
 * Container
 *
 * @param {string} message
 * @returns {JSX.Element}
 */
```

**Comment by heavenshell** [comment]
@malakada 
Thx. Yes, currently jsdoc.vim does not works perfectly.
But Now I'm planning to rewrite jsdoc.vim complety new(ver 2).

ver2 will be able to parse complex types.

**Comment by heavenshell** [comment]
2.0.0 was released
