### ISSUE TITLE
Error thrown for some functions

### ISSUE THREAD

**Issue by betterphp** [heavenshell/vim-jsdoc#78]
The following is thrown for some function definitions in classes. It seems pretty random and does it for really simple function, even empty ones with no parameters sometimes. It's a React project so these are methods on classes.

I can't seem to see a pattern so hoping this will mean something to somebody.

```
Error detected while processing function jsdoc#insert[135]..<SNR>102_hookArgs:
line    4:
E716: Key not present in Dictionary: param
E116: Invalid arguments for function printf(' * @%s %s', g:jsdoc_tags['param'], a:arg)
E15: Invalid expression: printf(' * @%s %s', g:jsdoc_tags['param'], a:arg)
Press ENTER or type command to continue
```

**Comment by heavenshell** [comment]
2.0.0 was released
hookArgs was deplecated
