### ISSUE TITLE
jsdoc.vim v2.0.0

### ISSUE THREAD

**Issue by heavenshell** [heavenshell/vim-jsdoc#81]
Hello, jsdoc.vim users.
I'm sorry for long time no update and response.

I'm currently working on jsdoc.vim v2.0.0

## What's new
- Complete re-write
- Can handle complex params

For example.
```typescript
const foo = (arg1: (arg1: { foo: string, bar: number }) => string, arg2: number) => {}
```

will generate like following.

```typescript
/**
 * foo.
 *
 * @param {Function} arg1
 * @param {number} arg2
 */
const foo = (arg1: (arg1: { foo: string, bar: number }) => string, arg2: number) => {}
```

- You can choose document block template from `JSDoc`, `ESDoc`, `TSDoc` and your own customaized template

## Deprecate
v2.0.0 will Deprecate all `g:jsdoc_*` variables.
`interactive mode` is also deprecate but you can use snippet plugin and custmaized template to insert document interactive.

Current version is too much global variables.
v2.x will be less global variables.

## Support Vim version
First release of v2.0.0 will only support **Vim8**.
I know some of user use Neovim, but I don't have Neovim env and knowledges.
So after release v2.0.0, If you want to use in Neovim, please send me PR.

## Release date
TBA. Hopefully I will release in near future.

Stay safe and take care.

![Kapture 2020-04-18 at 17 45 46](https://user-images.githubusercontent.com/56591/79635362-65786080-81ab-11ea-9fa0-0e7b00d9f6c9.gif)

**Comment by heavenshell** [comment]
https://github.com/heavenshell/vim-jsdoc/pull/82

**Comment by glepnir** [comment]
why not support neovim? ..Hope can support it.
