### ISSUE TITLE
Unknown function: job_start

### ISSUE THREAD

**Issue by good-idea** [heavenshell/vim-jsdoc#85]
I've updated to 2.0 and am getting this error when running `:JsDoc`:

```
Error detected while processing function jsdoc#insert[28]..275:
line    5:
E117: Unknown function: job_start
E15: Invalid expression: job_start(a:cmd, { 'callback': {_, m -> a:cb(m, a:start_lineno, a:is_method)}, 'exit_cb': {_, m -> a:ex_cb(m)}, 'in_mode': 'nl', })
line   11:
E121: Undefined variable: s:job
E116: Invalid arguments for function job_getchannel
E15: Invalid expression: job_getchannel(s:job)
line   12:
E121: Undefined variable: channel
E116: Invalid arguments for function ch_status
E15: Invalid expression: ch_status(channel) ==# 'open'
```

I installed `lehre` globally with `yarn global add lehre`, and added this to my .vimrc:

`let g:jsdoc_lehre_path = '/usr/local/bin/lehre'`

where `/usr/local/bin/lehre` is what is returned when I run `which lehre` in the command line.

Anything I can do here? Is this a problem with a global install of `lehre`?

**Comment by heavenshell** [comment]
@good-idea 
Thx for reporting.
What is your Vim version.
2.0.0 requires Vim8.0.1633(Neovim not supported)

**Comment by good-idea** [comment]
Oh, my mistake, I'm using Neovim.

**Comment by fpereira1** [comment]
Also using neovim, looks like progress is happening on https://github.com/heavenshell/vim-jsdoc/pull/89
