### ISSUE TITLE
How to use the interactive mode in 2.0.0?

### ISSUE THREAD

**Issue by IonicaBizau** [heavenshell/vim-jsdoc#96]
It is unclear to me how to use the snippet plugin.

Before I was using the global variable, but after upgrading to 2.0.0, I can't seem to figure it out.

**Comment by heavenshell** [comment]
Something like this?
![Kapture 2020-08-25 at 22 58 33](https://user-images.githubusercontent.com/56591/91184087-2e9cf300-e727-11ea-83dc-38f3fd2f0d13.gif)

I use neosnippet(sorry I don't know about other snippet plugin) and [this template].(https://github.com/heavenshell/vim-jsdoc/blob/master/examples/snippet_template.js)

**Comment by IonicaBizau** [comment]
But where should I put the template you linked?
Thank you!

**Comment by heavenshell** [comment]
Wherever you want to put 😉 

Set following to your vimrc.
```
let g:jsdoc_templates_path = '/path/to/snippet_template.js'
```
or
```
let g:jsdoc_templates_path = expand('~/path/to/snippet_template.js')
```

**Comment by IonicaBizau** [comment]
Thank you! :) That works!

**Comment by heavenshell** [comment]
welcome 😊

**Comment by duckscofield** [comment]
Hi all, I use the `UltiSnips` plugin, is there a case available?
