### ISSUE TITLE
Autodetect filetype and formatter

### ISSUE THREAD

**Issue by berndartmueller** [heavenshell/vim-jsdoc#98]
Hello,

first of all thanks a lot for this great plugin!

I'm wondering if there is a way to autodetect the current filetype and use an appropriate formatter (.js -> Javascript, .ts -> Typescript)?

Or at least a way to provide the formatter to the :JsDoc command.

Thanks!

**Comment by heavenshell** [comment]
@berndartmueller 
Hi, thank you for comment.

What do you mean about `use an appropriate formatter`.

Do you want to use something like *.js -> JsDoc format, *.ts -> TsDoc format?
Can you tell me little more detail?

**Comment by berndartmueller** [comment]
It would be great to have based on the current file (.js, .ts) either JsDoc or TsDoc used for formatting.

For now I set TsDoc as my default formatter, but occasionally I work on .js files and then it would be great to automatically format it with JsDoc.

**Comment by heavenshell** [comment]
@berndartmueller 

How about this?

Put followings to your .vimrc
```vim
function! s:jsdoc_type() abort
  if &filetype == 'typescript'
    let g:jsdoc_formatter = 'tsdoc'
  elseif &filetype == 'javascript'
    let g:jsdoc_formatter = 'jsdoc'
  endif                     
endfunction                 
autocmd BufWinEnter,BufNewFile *.ts,*.js call s:jsdoc_type()
```

**Comment by berndartmueller** [comment]
Awesome!

Thanks a lot @heavenshell

I extended your script slightly to have different formatter loaded too.

```viml
function! s:jsdoc_formatter() abort
  if &filetype == 'typescript'
    let g:jsdoc_formatter = 'tsdoc'
    let g:jsdoc_templates_path = '~/.vim/vim-jsdoc/ts-formatter.js'
  elseif &filetype == 'javascript'
    let g:jsdoc_formatter = 'jsdoc'
    let g:jsdoc_templates_path = '~/.vim/vim-jsdoc/js-formatter.js'
  endif
endfunction
```

**Comment by heavenshell** [comment]
Great!
